/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Tugas_b;

import java.awt.Toolkit;
import java.awt.event.WindowEvent;
import javax.swing.JOptionPane;

/**
 *
 * @author eL
 */
public class GUI extends javax.swing.JFrame {
    Identitasruangkelas id = new Identitasruangkelas();
    Kondisiruangkelas kon_RK = new Kondisiruangkelas();
    Jumlahkondisidanposisisarana jum_KP = new Jumlahkondisidanposisisarana();
    Lingkunganruangkelas LRK = new Lingkunganruangkelas();
    Kebersihanruangkelas keb_RK = new Kebersihanruangkelas();
    Kenyamananruangkelas ken_RK = new Kenyamananruangkelas();
    Keamananruangkelas kea_RK = new Keamananruangkelas();
    

   
    public GUI() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Login = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        pass = new javax.swing.JPasswordField();
        user = new javax.swing.JTextField();
        submit = new javax.swing.JButton();
        cancel = new javax.swing.JButton();
        Identitas = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        nama = new javax.swing.JTextField();
        lokasi = new javax.swing.JTextField();
        fakultas = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        Kondisi = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        nama1 = new javax.swing.JTextField();
        lokasi1 = new javax.swing.JTextField();
        fakultas1 = new javax.swing.JTextField();
        jButton2 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(600, 680));
        setPreferredSize(new java.awt.Dimension(600, 680));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Login.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        Login.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel1.setText("Login");
        Login.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 40, -1, -1));

        jLabel2.setText("Username");
        Login.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 120, -1, -1));

        jLabel3.setText("Password");
        Login.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 160, -1, -1));

        pass.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                passActionPerformed(evt);
            }
        });
        Login.add(pass, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 160, 132, -1));

        user.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                userActionPerformed(evt);
            }
        });
        Login.add(user, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 110, 132, -1));

        submit.setText("SUBMIT");
        submit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                submitActionPerformed(evt);
            }
        });
        Login.add(submit, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 210, -1, -1));

        cancel.setText("CANCEL");
        cancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancelActionPerformed(evt);
            }
        });
        Login.add(cancel, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 210, -1, -1));

        getContentPane().add(Login, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 140, 370, 270));

        Identitas.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        Identitas.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel4.setText("Nama Ruangan");
        Identitas.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 150, -1, -1));

        jLabel5.setText("Lokasi");
        Identitas.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 193, -1, -1));

        jLabel6.setText("Fakultas");
        Identitas.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 236, -1, -1));
        Identitas.add(nama, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 150, 190, -1));
        Identitas.add(lokasi, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 190, 190, -1));
        Identitas.add(fakultas, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 230, 190, -1));

        jButton1.setText("Next");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        Identitas.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 310, -1, -1));

        getContentPane().add(Identitas, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 90, 620, 420));

        Kondisi.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        Kondisi.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel7.setText("Nama Ruangan");
        Kondisi.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 150, -1, -1));

        jLabel8.setText("Lokasi");
        Kondisi.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 193, -1, -1));

        jLabel9.setText("Fakultas");
        Kondisi.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 236, -1, -1));
        Kondisi.add(nama1, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 150, 190, -1));
        Kondisi.add(lokasi1, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 190, 190, -1));
        Kondisi.add(fakultas1, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 230, 190, -1));

        jButton2.setText("Next");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        Kondisi.add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 310, -1, -1));

        getContentPane().add(Kondisi, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 90, 620, 420));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void userActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_userActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_userActionPerformed

    private void passActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_passActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_passActionPerformed

    private void submitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_submitActionPerformed
       String Username = user.getText();
       String Password = pass.getText();
        
        if (Username.equals("dedi95") || Username.equals("briyananda") && (Password.equals("briyo") || Password.equals("dedi"))){
            user.setText("");
            pass.setText("");
            Identitas.setVisible(true);
            Login.setVisible(false);
        }
        else {
            JOptionPane.showMessageDialog(null,"Username atau Password anda salah", "Klik OK dan coba lagi", JOptionPane.ERROR_MESSAGE);
            pass.setText("");
            user.setText("");            
        }      
        
        
    
    }//GEN-LAST:event_submitActionPerformed

    private void cancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancelActionPerformed
       close();
    }//GEN-LAST:event_cancelActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        Identitas.setVisible(rootPaneCheckingEnabled);
        
        id.setNamaRuang(Integer.parseInt(nama.getText()));
        id.setLokasiRuang(Integer.parseInt(lokasi.getText()));
        id.setFakultas(fakultas.getText());
        id.Output();
        id.Save();
        
        Kondisi.setVisible(true);
        Identitas.setVisible(false);
       
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton2ActionPerformed
    private void close(){
        WindowEvent winClosing = new WindowEvent(this, WindowEvent.WINDOW_CLOSING);
        Toolkit.getDefaultToolkit().getSystemEventQueue().postEvent(winClosing);
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new GUI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel Identitas;
    private javax.swing.JPanel Kondisi;
    private javax.swing.JPanel Login;
    private javax.swing.JButton cancel;
    private javax.swing.JTextField fakultas;
    private javax.swing.JTextField fakultas1;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JTextField lokasi;
    private javax.swing.JTextField lokasi1;
    private javax.swing.JTextField nama;
    private javax.swing.JTextField nama1;
    private javax.swing.JPasswordField pass;
    private javax.swing.JButton submit;
    private javax.swing.JTextField user;
    // End of variables declaration//GEN-END:variables
}
